# Site settings
name: Alex Anthis
title: Alex Anthis | Software Engineer
description: Goal driven back-end software engineer focused on building robust and performant solutions
url: https://alexanthis.com/
baseurl: ''
email: anthiswebdev@gmail.com
cover: https://alexanthis.com/img/og.png
logo: https://alexanthis.com/img/emojis/alpha_squared_64.png
resume: https://alexanthis.com/resume.pdf
social:
  - title: email
    url: mailto:anthiswebdev@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/alex-anthis  
  - title: github
    url: https://github.com/alexanth
  - title: instagram
    url: https://instagram.com/alpha_squared

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
