# Site settings
name: Paolo D'Elia
title: Paolo D'Elia | Data Scientist
description: Let's put the option apart and let's instead the data talk by itself
url: https://paolodelia99.github.io/
baseurl: ''
email: paolo.delia99@gmail.com
cover: https://paolodelia99.github.io/img/og.png
logo: https://paolodelia99.github.io/img/emojis/bar-chart-whatsapp.png
resume: https://paolodelia99.github.io/resume.pdf
social:
  - title: email
    url: mailto:paolo.delia99@gmail.com
  - title: twitter
    url: https://twitter.com/Delia99Paolo
  - title: github
    url: https://github.com/paolodelia99
  - title: linkedin
    url: https://www.linkedin.com/in/paolo-d-elia/
  - title: blog
    url: http://paolodelia99.github.io/blog/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
