# Site settings
name: Brittany Chiang
title: Brittany Chiang | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://bchiang7.github.io/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:brittany.chiang@gmail.com
  - title: twitter
    url: https://twitter.com/bchiang7
  - title: instagram
    url: https://instagram.com/bchiang7
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/bchiang7
  - title: linkedin
    url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
